### ISSUE TITLE
sensitive view red box won't hide after navigate to other screens on android

### ISSUE THREAD

**Issue by msabaeian** [uxcam/react-native-ux-cam#39]
I'm using the Hide Sensitive Data (HSD) feature; everything is fine on iOS but not in android; the problem is when I navigate to another screen, the red box of HSD stays there until I reset the entire Stack or close the screen, and then It'll be disappearing.

https://user-images.githubusercontent.com/73234920/152640914-e5241b17-22fc-42d7-a9cd-bba3ecc0f20c.mp4

ex: the red box of the Home tab stays there when I navigate to other screens, but when I click on Notification tab (change stack) it'll be disappear.

the correct behavior in iOS:

https://user-images.githubusercontent.com/73234920/152641332-d7020723-62f3-4190-a794-5b2dcd1b9fd4.mp4

Env:
"react-native": "^0.64.0",
"react": "17.0.1",
"react-native-ux-cam": "^5.3.4",
"react-navigation": "^4.4.4"

Is there any solution for this issue?

**Comment by DFDIEGOH** [comment]
Hi @msabaeian Let me explain a little bit more about this issue. Since in React Native everything is running under the same activity, the screens are under the same stack, meaning that the screens are on top of each other.

It can be the case that if you have different screens with occluded screens and then navigate to another screen, then that second screens is going to be on top of the previous one meaning that the previous stack doesn't necessarily leaves and that is why the hidden views are still visible unless, the stack is reseted, as you mentioned. 

At the moment there is no solution for this specific scenario since we need to investigate this further in order to adjust to the different ways of navigation that React Native has. 

I apologize for the inconvenience but please let me know if you have further questions in this regard.

**Comment by ziga-hvalec** [comment]
Any update on this one?
