### ISSUE TITLE
Red screen when calling RNUxcam.resumeScreenRecording();  RNUxcam.pauseScreenRecording();

### ISSUE THREAD

**Issue by shay-te** [uxcam/react-native-ux-cam#64]
Hello all. 
We are experiencing a red screen when calling the functions `RNUxcam.resumeScreenRecording();  RNUxcam.pauseScreenRecording();`

Thank you

![image](https://user-images.githubusercontent.com/5166849/187234258-c1d819a2-28e0-4114-8cb8-79b9cd704f24.png)

**Comment by gabrieluxcam** [comment]
Hello @shay-te  apologies for the delayed response, we're working on improving our github response time since our main thread of communications for support has commonly been through intercom/email.

Pausing screen recording will create this red overlay, as the screen will not be captured but the session itself will be. Calling resume should remove it at a later point in your app. Thanks!
